// const BASE_AVATAR_URL = `https://avataaars.io/?avatarStyle=Circle&topType=LongHairDreads&accessoriesType=Wayfarers&hairColor=Platinum&facialHairType=BeardMedium&facialHairColor=Black&clotheType=ShirtVNeck&clotheColor=PastelOrange&eyeType=Dizzy&eyebrowType=SadConcernedNatural&mouthType=Smile&skinColor=Black`;
// const AVATAR_URL = `https://avataaars.io/?avatarStyle=Circle&topType=${topType}&accessoriesType=${accessoriesType}&hairColor=${hairColor}&facialHairType=${facialHairType}&facialHairColor=${facialHairColor}&clotheType=${clotheType}&clotheColor=${clotheColor}&eyeType=${eyeType}&eyebrowType=${eyebrowType}&mouthType=${mouthType}&skinColor=${skinColor}`;

const avatars = [
  "https://avataaars.io/?avatarStyle=Circle&topType=ShortHairFrizzle&accessoriesType=Sunglasses&hairColor=SilverGray&facialHairType=MoustacheMagnum&facialHairColor=Red&clotheType=ShirtScoopNeck&clotheColor=Pink&eyeType=Cry&eyebrowType=SadConcerned&mouthType=Disbelief&skinColor=Yellow",
  "https://avataaars.io/?avatarStyle=Circle&topType=LongHairStraightStrand&accessoriesType=Kurt&hairColor=BrownDark&facialHairType=Blank&facialHairColor=Black&clotheType=ShirtScoopNeck&clotheColor=Black&eyeType=Wink&eyebrowType=FlatNatural&mouthType=Eating&skinColor=Yellow",
  "https://avataaars.io/?avatarStyle=Circle&topType=WinterHat1&accessoriesType=Prescription01&hatColor=Red&hairColor=Red&facialHairType=MoustacheFancy&facialHairColor=Red&clotheType=CollarSweater&clotheColor=Blue02&eyeType=EyeRoll&eyebrowType=FlatNatural&mouthType=Twinkle&skinColor=Yellow",
  "https://avataaars.io/?avatarStyle=Circle&topType=ShortHairSides&accessoriesType=Prescription01&hatColor=Gray02&hairColor=PastelPink&facialHairType=MoustacheFancy&facialHairColor=Auburn&clotheType=BlazerSweater&clotheColor=Blue02&eyeType=WinkWacky&eyebrowType=DefaultNatural&mouthType=Sad&skinColor=DarkBrown",
  "https://avataaars.io/?avatarStyle=Circle&topType=WinterHat4&accessoriesType=Round&hatColor=Gray01&hairColor=Platinum&facialHairType=BeardMagestic&facialHairColor=Brown&clotheType=ShirtCrewNeck&clotheColor=PastelBlue&eyeType=Surprised&eyebrowType=UpDown&mouthType=Sad&skinColor=Tanned",
  "https://avataaars.io/?avatarStyle=Circle&topType=LongHairDreads&accessoriesType=Sunglasses&hatColor=Pink&hairColor=PastelPink&facialHairType=Blank&facialHairColor=BrownDark&clotheType=Hoodie&clotheColor=PastelOrange&eyeType=Happy&eyebrowType=SadConcerned&mouthType=Serious&skinColor=Yellow",
  "https://avataaars.io/?avatarStyle=Circle&topType=ShortHairSides&accessoriesType=Sunglasses&hairColor=Red&facialHairType=BeardMagestic&facialHairColor=Platinum&clotheType=Hoodie&clotheColor=PastelYellow&eyeType=Dizzy&eyebrowType=RaisedExcited&mouthType=Sad&skinColor=Tanned",
  "https://avataaars.io/?avatarStyle=Circle&topType=LongHairFro&accessoriesType=Prescription01&hairColor=Blonde&facialHairType=MoustacheMagnum&facialHairColor=BrownDark&clotheType=ShirtScoopNeck&clotheColor=Black&eyeType=Wink&eyebrowType=RaisedExcitedNatural&mouthType=Tongue&skinColor=Tanned",
  "https://avataaars.io/?avatarStyle=Circle&topType=LongHairFrida&accessoriesType=Kurt&hairColor=Red&facialHairType=BeardMagestic&facialHairColor=Platinum&clotheType=GraphicShirt&clotheColor=Gray02&graphicType=Skull&eyeType=Surprised&eyebrowType=UpDownNatural&mouthType=Smile&skinColor=Tanned",
  "https://avataaars.io/?avatarStyle=Circle&topType=WinterHat1&accessoriesType=Round&hatColor=Gray02&facialHairType=MoustacheFancy&facialHairColor=BrownDark&clotheType=GraphicShirt&clotheColor=Heather&graphicType=Hola&eyeType=Close&eyebrowType=UpDown&mouthType=Tongue&skinColor=Pale",
  "https://avataaars.io/?avatarStyle=Circle&topType=LongHairDreads&accessoriesType=Prescription02&hatColor=Gray01&hairColor=Red&facialHairType=BeardMagestic&facialHairColor=BrownDark&clotheType=Hoodie&clotheColor=Heather&graphicType=Deer&eyeType=Default&eyebrowType=UpDownNatural&mouthType=ScreamOpen&skinColor=Yellow",
  "https://avataaars.io/?avatarStyle=Circle&topType=ShortHairShaggyMullet&accessoriesType=Prescription01&hairColor=SilverGray&facialHairType=MoustacheFancy&facialHairColor=Red&clotheType=BlazerSweater&clotheColor=Blue01&eyeType=Surprised&eyebrowType=SadConcerned&mouthType=Grimace&skinColor=Light",
  "https://avataaars.io/?avatarStyle=Circle&topType=WinterHat2&accessoriesType=Round&hatColor=Pink&hairColor=BlondeGolden&facialHairType=Blank&facialHairColor=Black&clotheType=ShirtVNeck&clotheColor=Pink&eyeType=Side&eyebrowType=Default&mouthType=Tongue&skinColor=Black",
  "https://avataaars.io/?avatarStyle=Circle&topType=LongHairCurly&accessoriesType=Kurt&hairColor=PastelPink&facialHairType=Blank&facialHairColor=BrownDark&clotheType=ShirtVNeck&clotheColor=Red&eyeType=Cry&eyebrowType=DefaultNatural&mouthType=Sad&skinColor=Tanned"
];

export const randomAvatar = avatars[Math.floor(Math.random() * avatars.length)];
